name: topic_space
dependencies:
- bcolz=0.7.2.dev=np19py27_0
- blaze=0.7.0=np19py27_0
- bokeh=0.7.1=np19py27_0
- cffi=0.8.6=py27_0
- colorama=0.3.1=py27_0
- cryptography=0.5.4=py27_0
- cssselect=0.9.1=py27_0
- cytoolz=0.7.1=py27_0
- datashape=0.4.2=np19py27_0
- dateutil=2.1=py27_2
- decorator=3.4.0=py27_0
- flask=0.10.1=py27_1
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- greenlet=0.4.5=py27_0
- h5py=2.3.1=np19py27_1
- hdf5=1.8.14=0
- into=0.1.3=np19py27_0
- ipython=2.3.1=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.7.3=py27_1
- libsodium=0.4.5=0
- libxml2=2.9.0=1
- libxslt=1.1.28=2
- lxml=3.4.1=py27_0
- markupsafe=0.23=py27_0
- mkl-rt=11.1=p0
- mkl-service=1.0.0=py27_p1
- multipledispatch=0.4.7=py27_0
- networkx=1.9.1=py27_0
- nose=1.3.4=py27_0
- numexpr=2.3.1=np19py27_0
- numpy=1.9.1=py27_0
- openssl=1.0.1k=0
- pandas=0.15.2=np19py27_0
- pip=6.0.6=py27_0
- psutil=2.1.1=py27_0
- pycparser=2.10=py27_0
- pygments=2.0.1=py27_0
- pyopenssl=0.14=py27_0
- pytables=3.1.1=np19py27_2
- python=2.7.9=1
- python.app=1.2=py27_3
- pytz=2014.9=py27_0
- pyyaml=3.11=py27_0
- pyzmq=14.5.0=py27_0
- queuelib=1.2.2=py27_0
- readline=6.2=2
- requests=2.5.1=py27_0
- scikit-learn=0.15.0b1=np18py27_0
- scipy=0.15.1=np19py27_0
- scrapy=0.24.4=py27_0
- setuptools=12.0.3=py27_0
- six=1.9.0=py27_0
- sqlalchemy=0.9.8=py27_0
- sqlite=3.8.4.1=0
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.15=0
- toolz=0.7.1=py27_0
- tornado=4.0.2=py27_0
- twisted=14.0.0=py27_0
- ujson=1.33=py27_0
- w3lib=1.8.1=py27_1
- werkzeug=0.9.6=py27_1
- xz=5.0.5=0
- yaml=0.1.4=1
- zeromq=4.0.4=0
- zlib=1.2.8=0
- zope.interface=4.1.1=py27_0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.2
  - cython==0.21.2
  - django==1.7.3
  - gensim==0.10.3
  - image==1.3.4
  - nltk==3.0.1
  - pattern==2.6
  - pillow==2.7.0
  - python-dateutil==1.5
  - tables==3.1.1
  - textblob==0.9.0
  - wordcloud==1.0.0
  - git+git://github.com/amueller/word_cloud.git
